### ISSUE TITLE
World age error

### ISSUE THREAD

**Issue by cstjean** [marius311/Memoization.jl#10]
```julia
julia> using Memoization, DataStructures

julia> @memoize OrderedDict f(; x=1) = x   # of course there's no point to using an OrderedDict...
f (generic function with 1 method)

julia> f()
ERROR: MethodError: no method matching OrderedDict()
The applicable method may be too new: running in world age 27811, while current world is 27818.
```

I'm curious why you're going through the trouble of using a generated function, instead of just creating a global with the cache. Also, if I'm reading https://github.com/marius311/Memoization.jl/blob/master/src/Memoization.jl#L24-L33 right, all methods with the same cache-type will share the cache, but those with a different cache-type will use a different one?

**Comment by marius311** [comment]
> I'm curious why you're going through the trouble of using a generated function, instead of just creating a global with the cache

Performance, because for top-level functions, looking up the right cache in `Memoization.caches` gets compiled away entirely. This leads to the world age problems unfortunately, not sure if there's a way around it. This is mentioned in the readme FWIW, i.e. that you should do `using DataStructures, Memoization` instead of the other way around. I'd like to keep the performance, but maybe there's a way to add a fall-back with `invokelatest` or something, so if you imported things in the wrong error, it'll still work, you just won't get the performance? 

> all methods with the same cache-type will share the cache, but those with a different cache-type will use a different one?

Yea, I think this was mainly a code thing driven by having used the generated function, but I agree its a little weird. Probably the better behavior is to memoize per-function, rather than per-(function,cachetype).

**Comment by cstjean** [comment]
> Performance, because for top-level functions, looking up the right cache in Memoization.caches gets compiled away entirely.

Yeah, but if you used a simple `const` global, it would be the same.

> This leads to the world age problems unfortunately, not sure if there's a way around it. This is mentioned in the readme FWIW, i.e. that you should do using DataStructures, Memoization instead of the other way around. 

Ah, sorry I missed that. I'll close it then.

**Comment by marius311** [comment]
>Yeah, but if you used a simple const global, it would be the same.

Are you sure that's true? With this solution the right cache is essentially pasted into the expression tree at compile time. If it were a constant global wouldn't it have to look up the cache each time?

**Comment by cstjean** [comment]
Pretty sure; that's why constant redefinition says:

> WARNING: redefinition of constant xx. This may fail, cause incorrect answers, or produce other errors.

; because it's pasted into the expression tree, as you say. However, it causes issues for [memoizing local functions](https://github.com/JuliaCollections/Memoize.jl/pull/59), which I don't know if you support.

**Comment by marius311** [comment]
I think I must not be understanding something, sorry. I'm talking about looking up right cache for a given function, not looking up the memoized answer for a given set of arguments. Its definitely less overhead to do the former with a generated function, e.g.:

```julia
using BenchmarkTools
function foo end
const caches = IdDict(foo => Dict())
@generated get_cache_generated() = caches[foo]
get_cache() = caches[foo]

@btime get_cache() # 14ns
@btime get_cache_generated() # 1ns
```

This package does do local functions and closures (see readme), in that case we do in fact do the lookup at runtime as opposed to compile time, that's the if-statement in `get_cache` which controls if we return that cache directly or return the code to return the cache, 

https://github.com/marius311/Memoization.jl/blob/138f17603227de74314e68f633aed462cb83fa97/src/Memoization.jl#L25-L32

**Comment by cstjean** [comment]
I meant: why not just have `@memoize foo(x) = x` expand into

```julia
const foo_cache = Dict()
foo(x) = get!(foo_cache, x) do 
    ...
end
```

? Then you don't need `get_cache` at all. But you're right, perhaps it won't work for some of the use case you cover. Anyway, I was just looking into improving `Memoize.jl` and comparing design trade-offs, thank you for the discussion. I should have read the README more carefully!

**Comment by marius311** [comment]
No worries, I'm into brainstorming how best to do this. I think I thought about that solution, but the problem is how do you know what name to give `foo_cache` and which module to put it in? Certainly you could just use the function name itself and put it in the current module, but then it doesn't work if you define different methods of a function across different modules (this is indeed a use case Memoization covers that afaik Memoize doesn't).

**Comment by cstjean** [comment]
In our internal memoization macro, we simply used

```julia
    cache = Symbol(di_in[:name], "__memo__",
                   # We put in the method signature in the name because we want:
                   #    @memoize foo(::Int) = ...
                   # and
                   #    @memoize foo(::Float64) = ...
                   # to have separate caches
                   join((filter(isletter, string(splitarg(a)[2]))
                         for a in di_in[:args]), "_"))
```
which generates something like `foo_memo_Int_Any`, so each method has its own cache by default, which I find appealing. 

> it doesn't work if you define different methods of a function across different modules (this is indeed a use case Memoization covers that afaik Memoize doesn't).

Memoize.jl gets around that by having a different cache per `(module, function)`. It's more of an implementation accident than a conscious design decision AFAICT, but it works.
