### ISSUE TITLE
Unable to Redefine Cache Type

### ISSUE THREAD

**Issue by TheCedarPrince** [marius311/Memoization.jl#21]
Hi @marius311 and all,

I am using Memoization to memoize a given function.
When I memoize the following function:

```julia
@memoize f(x) = (println("Computed $x"); x) # memoize a function
```

I am unable to change the cache type:

```julia
@memoize Dict f(x) = (println("Computed $x"); x) # memoize a function
```

Which results in this error: 

```
ERROR: f is already memoized with IdDict
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] top-level scope
   @ ~/.julia/packages/Memoization/ut5GT/src/Memoization.jl:119  
```

Is this behavior expected?
I didn't see this listed in the docs as a limitation so wasn't sure if this was a bug or not.
Thanks for the great package!
Using it in the future going forward. :)

**Comment by marius311** [comment]
Thanks for the note. This is intentional and a current limitation, I added a note about it in the readme. Maybe this could be changed in the future.

**Comment by TheCedarPrince** [comment]
Thanks for adding the note @marius311 !
Out of pure curiosity, why is this intentional?
I don't have a problem with it whatsoever but just was wondering what the design decision was.

Either way, I owe you a huge thank you for this project @marius311 !
By simply adding `@memoize Dict` to my functions, my script went from taking upwards of 30+ hours to nearly 15 to 20 minutes. 
That was so satisfying to do and watch happen! 💯

**Comment by marius311** [comment]
The way it works is that every _function_ gets an entry in `Memoization.caches` that stores the cache for all that function's methods. Now if you have two _methods_ eg:
```
@memoize Dict foo(x::Int) = ...
@memoize IdDict foo(x::String) = ...
```
or something, what should happen? The first definition ensures that `Memoization.caches[foo]` is a `Dict`. Should the second definition replace that with an `IdDict`? That seems pretty ambiguous especially if these are methods defined in some package. Or should the first method indeed be memoized with Dict while the second with IdDict? Could be possible but then we need to have `Memoization.caches` be a mapping of methods -> caches rather than functions -> caches, which seem significnatly more complex. In lieu of a good solution, for now its just an error.

**Comment by TheCedarPrince** [comment]
Thanks for the explanation!
That makes a lot of sense!
